### PR TITLE
Modernize spellings

### PR DESCRIPTION
**Pull request by bentley**
I noticed that many editions on Google Books, maybe even the majority, modernize “sovran” to “sovereign” or “sov’reign.” This was gratifying, as I found the “sovran” spelling incredibly distracting the whole time I read the book.

“Sov’reign” is a better choice than “sovereign” as it preserves the meter.

### CODE REVIEW

**Comment by acabal** [comment]
OK, but I think if we're modernizing it we may as well just spell it completely, without the apostrophe. It's pronounced as two syllables anyway despite it being written as if it were three.

Did you see my email re. collections?

**Comment by bentley** [comment]
Updated to “sovereign.”

> Did you see my email re. collections?

Yes, and responded. Did it go to spam? That would explain why you never responded to my last email…

**Comment by acabal** [comment]
No, I haven't received any email, not even in spam.

**Comment by bentley** [comment]
Ah, your MX records are out of date. MX is set to `mx.zohomail.com` and `mx2.zohomail.com`, which present a certificate valid only for `*.zoho.com`, breaking senders that mandate TLS.

> To ensure correct email delivery to your domain, only the MX Records provided below should be listed.
>
> |MX|Priority|
> |-|-|
> |mx.zoho.com.|10|
> |mx2.zoho.com.|20|
> |mx3.zoho.com.|50|
>
> https://www.zoho.com/mail/help/adminconsole/configure-email-delivery.html#alink2

**Comment by acabal** [comment]
OK, I've updated the records, you can try again now. If I don't reply in a half an hour then it still hasn't worked.

**Pull request merged**
